name: Hotel Booking CI
on:
  push:
    branches:
      master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout SC
        
      - uses: actions/setup-java@v2
      - name: Set up java 21  
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
     - name: Check Java version
       run: java -version
      - name: Check Maven version
        run: mvn -version
      - name: Compile  
        run: mvn compile 
      - name: Package
        run: mvn clean package
        
